import { useState, useEffect, useCallback } from "react";
import ReactMarkdown from "react-markdown";
import styles from "./ReportViewer.module.css";

interface Props {
  reportPath: string | null;
}

const HTML_STYLES = `
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 860px; margin: 40px auto; padding: 0 24px 80px; color: #1e293b; line-height: 1.7; }
  h1 { font-size: 28px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px; border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; }
  h2 { font-size: 20px; font-weight: 700; color: #0f172a; margin-top: 40px; padding: 10px 16px; background: #f8fafc; border-left: 3px solid #6366f1; border-radius: 0 8px 8px 0; }
  h3 { font-size: 16px; font-weight: 600; color: #334155; margin-top: 28px; }
  h4 { font-size: 14px; font-weight: 600; color: #6366f1; margin-top: 20px; text-transform: uppercase; letter-spacing: 0.05em; }
  p { color: #475569; margin: 10px 0; }
  strong { color: #1e293b; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }
  th { background: #f1f5f9; padding: 10px 14px; text-align: left; font-weight: 600; color: #374151; border: 1px solid #e2e8f0; }
  td { padding: 9px 14px; border: 1px solid #e2e8f0; color: #475569; }
  tr:nth-child(even) td { background: #f8fafc; }
  code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 13px; font-family: 'JetBrains Mono', monospace; color: #6366f1; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 32px 0; }
  blockquote { border-left: 3px solid #c7d2fe; margin: 0; padding: 8px 16px; color: #64748b; background: #f8fafc; border-radius: 0 8px 8px 0; }
  .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
`;

function buildHtml(markdown: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>${HTML_STYLES}</style>
</head>
<body>
<div id="content">
${markdownToHtml(markdown)}
</div>
<div class="footer">Generated by 🧬 Cambrian — github.com/janshibhavsar24-gif/cambrian</div>
</body>
</html>`;
}

// Minimal markdown → HTML for the download (headings, bold, tables, hr, paragraphs)
function markdownToHtml(md: string): string {
  return md
    .replace(/^#### (.+)$/gm, "<h4>$1</h4>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^---$/gm, "<hr>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^\|(.+)\|$/gm, (row) => {
      const cells = row.slice(1, -1).split("|").map(c => `<td>${c.trim()}</td>`).join("");
      return `<tr>${cells}</tr>`;
    })
    .replace(/(<tr>.*<\/tr>\n?)+/g, (table) => `<table>${table}</table>`)
    .replace(/^(?!<[h|t|u|o|h|b|d|p])(.*\S.*)$/gm, "<p>$1</p>")
    .replace(/<p><\/p>/g, "");
}

export function ReportViewer({ reportPath }: Props) {
  const [open, setOpen] = useState(false);
  const [markdown, setMarkdown] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchReport = useCallback(async () => {
    if (!reportPath) return;
    setLoading(true);
    try {
      const res = await fetch(`http://localhost:8000/api/report?path=${encodeURIComponent(reportPath)}`);
      const text = await res.text();
      setMarkdown(text);
    } finally {
      setLoading(false);
    }
  }, [reportPath]);

  useEffect(() => {
    if (open && !markdown) fetchReport();
  }, [open, markdown, fetchReport]);

  const handleDownload = () => {
    if (!markdown) return;
    const title = "Cambrian Report";
    const html = buildHtml(markdown, title);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "cambrian-report.html";
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!reportPath) return null;

  return (
    <>
      <button className={styles.trigger} onClick={() => setOpen(true)}>
        View Full Report
      </button>

      {open && (
        <div className={styles.overlay} onClick={() => setOpen(false)}>
          <div className={styles.modal} onClick={e => e.stopPropagation()}>
            <div className={styles.modalHeader}>
              <span className={styles.modalTitle}>Full Report</span>
              <div className={styles.modalActions}>
                <button className={styles.downloadBtn} onClick={handleDownload} disabled={!markdown}>
                  Download HTML
                </button>
                <button className={styles.closeBtn} onClick={() => setOpen(false)}>✕</button>
              </div>
            </div>
            <div className={styles.body}>
              {loading && <div className={styles.loading}>Loading report…</div>}
              {markdown && (
                <ReactMarkdown>{markdown}</ReactMarkdown>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
